# Manip2: Chargement de fichier et sauvegarde avec numpy

In [5]:
import numpy as np
data = np.loadtxt('production.txt')
print(data)
data[2,3] = 936
#np.set_printoptions(suppress=True)
np.savetxt('production2.txt', data,'%8d')

[[ 1900.   455.   346.   877.]
 [ 1901.   676.   777.   777.]
 [ 1902.   466.   755.   567.]
 [ 1903.   900.   988.  1200.]]
